/**
 * intake-data.js
 *
 * The ONLY file you edit for each new intake.
 * push-to-sanity.js imports from here — do not edit that file.
 *
 * Before editing: run `npm run check -- --foundry <slug> --typeface <slug>`
 */

// ── Foundry ───────────────────────────────────────────────────────────────────
const FOUNDRY = null;
const FOUNDRY_ID = 'foundry-east-of-rome';

// ── Shared fields (common to all typefaces in this intake) ────────────────────
// width omitted — varies per record
const SHARED = {
  weightRange:         ['medium', 'semibold', 'bold', 'black'],
  era:                 ['Contemporary'],
  licensing:           'paid',
  platforms:           'neither',
  variableFont:        false,
  multilingualSupport: true,
  featured:            false,
};

// ── Typefaces ─────────────────────────────────────────────────────────────────
const TYPEFACES = [
  {
    _id:               'typeface-tusker-pro-1000',
    name:              'Tusker Pro 1000',
    slug:              'tusker-pro-1000',
    specimenFile:      'east-of-rome_tusker-pro-1000_specimen.jpg',
    specimenHeavyFile: 'east-of-rome_tusker-pro-1000_specimen_heavy.jpg',
    editorialNote:     'The tightest setting in Tusker Pro\'s nine-width duplexed display grotesk by Lewis McGuffie. At this extreme compression, the huge x-height and duplexed weights make it ideal for stacked headlines, tight logos, and maximum-density poster type.',
    classification:    ['sans-serif', 'display'],
    subClassification: 'Multi-Width Display Grotesque',
    personalityTags:   ['Loud', 'Authoritative', 'Expressive', 'Raw', 'Functional'],
    useCaseTags:       ['Headline', 'Poster', 'Logo', 'Branding', 'Signage'],
    width:             'condensed',
    xHeight:           'tall',
    contrast:          ['monolinear'],
    typefaceURL:       'https://www.eastofrome.com/fonts/tusker-pro',
    hasItalics:        true,
    rawKeywords:       ['East of Rome', 'EOR', 'Lewis McGuffie', '2017', 'Tusker Pro', 'Tusker Grotesk', 'duplexed', '1000', 'ultra condensed', 'condensed grotesque', 'display grotesque', 'Super', 'Cyrillic', 'Greek'],
  },
  {
    _id:               'typeface-tusker-pro-2000',
    name:              'Tusker Pro 2000',
    slug:              'tusker-pro-2000',
    specimenFile:      'east-of-rome_tusker-pro-2000_specimen.jpg',
    specimenHeavyFile: 'east-of-rome_tusker-pro-2000_specimen_heavy.jpg',
    editorialNote:     'The second narrowest width in Tusker Pro\'s nine-step duplexed display grotesk by Lewis McGuffie. Still firmly in condensed display territory, with a huge x-height and four duplexed weights — suited to headlines where space is tight but the 1000 reads too compressed.',
    classification:    ['sans-serif', 'display'],
    subClassification: 'Multi-Width Display Grotesque',
    personalityTags:   ['Loud', 'Authoritative', 'Expressive', 'Raw', 'Functional'],
    useCaseTags:       ['Headline', 'Poster', 'Logo', 'Branding', 'Signage'],
    width:             'condensed',
    xHeight:           'tall',
    contrast:          ['monolinear'],
    typefaceURL:       'https://www.eastofrome.com/fonts/tusker-pro',
    hasItalics:        true,
    rawKeywords:       ['East of Rome', 'EOR', 'Lewis McGuffie', '2017', 'Tusker Pro', 'Tusker Grotesk', 'duplexed', '2000', 'condensed grotesque', 'display grotesque', 'Super', 'Cyrillic', 'Greek'],
  },
  {
    _id:               'typeface-tusker-pro-3000',
    name:              'Tusker Pro 3000',
    slug:              'tusker-pro-3000',
    specimenFile:      'east-of-rome_tusker-pro-3000_specimen.jpg',
    specimenHeavyFile: 'east-of-rome_tusker-pro-3000_specimen_heavy.jpg',
    editorialNote:     'The narrow range of Tusker Pro\'s nine-width duplexed display grotesk by Lewis McGuffie. Compressed enough for editorial columns and tight branding, with more open counters than the 1000 and 2000 series.',
    classification:    ['sans-serif', 'display'],
    subClassification: 'Multi-Width Display Grotesque',
    personalityTags:   ['Loud', 'Authoritative', 'Expressive', 'Functional', 'Neutral'],
    useCaseTags:       ['Headline', 'Poster', 'Branding', 'Signage', 'Logo'],
    width:             'narrow',
    xHeight:           'tall',
    contrast:          ['monolinear'],
    typefaceURL:       'https://www.eastofrome.com/fonts/tusker-pro',
    hasItalics:        true,
    rawKeywords:       ['East of Rome', 'EOR', 'Lewis McGuffie', '2017', 'Tusker Pro', 'Tusker Grotesk', 'duplexed', '3000', 'narrow grotesque', 'display grotesque', 'Super', 'Cyrillic', 'Greek'],
  },
  {
    _id:               'typeface-tusker-pro-4000',
    name:              'Tusker Pro 4000',
    slug:              'tusker-pro-4000',
    specimenFile:      'east-of-rome_tusker-pro-4000_specimen.jpg',
    specimenHeavyFile: 'east-of-rome_tusker-pro-4000_specimen_heavy.jpg',
    editorialNote:     'A slightly-below-normal width in Tusker Pro\'s nine-step duplexed display grotesk by Lewis McGuffie. Versatile enough for display-adjacent text and tight headline settings where the condensed variants feel too extreme.',
    classification:    ['sans-serif', 'display'],
    subClassification: 'Multi-Width Display Grotesque',
    personalityTags:   ['Authoritative', 'Functional', 'Neutral', 'Expressive', 'Serious'],
    useCaseTags:       ['Headline', 'Branding', 'Signage', 'Poster', 'Editorial'],
    width:             'narrow',
    xHeight:           'tall',
    contrast:          ['monolinear'],
    typefaceURL:       'https://www.eastofrome.com/fonts/tusker-pro',
    hasItalics:        true,
    rawKeywords:       ['East of Rome', 'EOR', 'Lewis McGuffie', '2017', 'Tusker Pro', 'Tusker Grotesk', 'duplexed', '4000', 'display grotesque', 'Super', 'Cyrillic', 'Greek'],
  },
  {
    _id:               'typeface-tusker-pro-5000',
    name:              'Tusker Pro 5000',
    slug:              'tusker-pro-5000',
    specimenFile:      'east-of-rome_tusker-pro-5000_specimen.jpg',
    specimenHeavyFile: 'east-of-rome_tusker-pro-5000_specimen_heavy.jpg',
    editorialNote:     'The middle width of Tusker Pro\'s nine-step duplexed display grotesk by Lewis McGuffie — sitting at normal proportions. The most versatile setting of the family, equally at home in display headlines, branding, and short editorial copy.',
    classification:    ['sans-serif', 'display'],
    subClassification: 'Multi-Width Display Grotesque',
    personalityTags:   ['Authoritative', 'Functional', 'Neutral', 'Serious', 'Approachable'],
    useCaseTags:       ['Headline', 'Branding', 'Signage', 'Editorial', 'Short Copy'],
    width:             'normal',
    xHeight:           'tall',
    contrast:          ['monolinear'],
    typefaceURL:       'https://www.eastofrome.com/fonts/tusker-pro',
    hasItalics:        true,
    rawKeywords:       ['East of Rome', 'EOR', 'Lewis McGuffie', '2017', 'Tusker Pro', 'Tusker Grotesk', 'duplexed', '5000', 'normal width grotesque', 'display grotesque', 'Super', 'Cyrillic', 'Greek'],
  },
  {
    _id:               'typeface-tusker-pro-6000',
    name:              'Tusker Pro 6000',
    slug:              'tusker-pro-6000',
    specimenFile:      'east-of-rome_tusker-pro-6000_specimen.jpg',
    specimenHeavyFile: 'east-of-rome_tusker-pro-6000_specimen_heavy.jpg',
    editorialNote:     'The first of Tusker Pro\'s wider settings — a normal-to-wide duplexed display grotesk by Lewis McGuffie with four weights and a huge x-height. Suited to large-format posters and signage where letterforms need to fill horizontal space.',
    classification:    ['sans-serif', 'display'],
    subClassification: 'Multi-Width Display Grotesque',
    personalityTags:   ['Loud', 'Authoritative', 'Functional', 'Expressive', 'Serious'],
    useCaseTags:       ['Poster', 'Headline', 'Signage', 'Branding', 'Logo'],
    width:             'normal',
    xHeight:           'tall',
    contrast:          ['monolinear'],
    typefaceURL:       'https://www.eastofrome.com/fonts/tusker-pro',
    hasItalics:        true,
    rawKeywords:       ['East of Rome', 'EOR', 'Lewis McGuffie', '2017', 'Tusker Pro', 'Tusker Grotesk', 'duplexed', '6000', 'wide grotesque', 'display grotesque', 'Super', 'Cyrillic', 'Greek'],
  },
  {
    _id:               'typeface-tusker-pro-7000',
    name:              'Tusker Pro 7000',
    slug:              'tusker-pro-7000',
    specimenFile:      'east-of-rome_tusker-pro-7000_specimen.jpg',
    specimenHeavyFile: 'east-of-rome_tusker-pro-7000_specimen_heavy.jpg',
    editorialNote:     'Moving into the wide range of Tusker Pro\'s nine-step duplexed display grotesk by Lewis McGuffie. The expanded proportions and duplexed weights create an open, bold presence suited to large-format display and spatial graphics.',
    classification:    ['sans-serif', 'display'],
    subClassification: 'Multi-Width Display Grotesque',
    personalityTags:   ['Loud', 'Authoritative', 'Expressive', 'Functional', 'Serious'],
    useCaseTags:       ['Poster', 'Signage', 'Headline', 'Branding', 'Logo'],
    width:             'wide',
    xHeight:           'tall',
    contrast:          ['monolinear'],
    typefaceURL:       'https://www.eastofrome.com/fonts/tusker-pro',
    hasItalics:        true,
    rawKeywords:       ['East of Rome', 'EOR', 'Lewis McGuffie', '2017', 'Tusker Pro', 'Tusker Grotesk', 'duplexed', '7000', 'wide grotesque', 'display grotesque', 'Super', 'Cyrillic', 'Greek'],
  },
  {
    _id:               'typeface-tusker-pro-8000',
    name:              'Tusker Pro 8000',
    slug:              'tusker-pro-8000',
    specimenFile:      'east-of-rome_tusker-pro-8000_specimen.jpg',
    specimenHeavyFile: 'east-of-rome_tusker-pro-8000_specimen_heavy.jpg',
    editorialNote:     'One of Tusker Pro\'s widest settings — an expanded duplexed display grotesk by Lewis McGuffie that commands horizontal space. At this width, the huge x-height and thick strokes create an imposing, wall-filling presence.',
    classification:    ['sans-serif', 'display'],
    subClassification: 'Multi-Width Display Grotesque',
    personalityTags:   ['Loud', 'Authoritative', 'Expressive', 'Raw', 'Functional'],
    useCaseTags:       ['Poster', 'Signage', 'Headline', 'Branding', 'Logo'],
    width:             'wide',
    xHeight:           'tall',
    contrast:          ['monolinear'],
    typefaceURL:       'https://www.eastofrome.com/fonts/tusker-pro',
    hasItalics:        true,
    rawKeywords:       ['East of Rome', 'EOR', 'Lewis McGuffie', '2017', 'Tusker Pro', 'Tusker Grotesk', 'duplexed', '8000', 'wide grotesque', 'extended grotesque', 'display grotesque', 'Super', 'Cyrillic', 'Greek'],
  },
  {
    _id:               'typeface-tusker-pro-9000',
    name:              'Tusker Pro 9000',
    slug:              'tusker-pro-9000',
    specimenFile:      'east-of-rome_tusker-pro-9000_specimen.jpg',
    specimenHeavyFile: 'east-of-rome_tusker-pro-9000_specimen_heavy.jpg',
    editorialNote:     'The widest setting in Tusker Pro\'s nine-step duplexed display grotesk by Lewis McGuffie — an extended grotesque that maximises horizontal spread. Best used at large sizes for posters, signage, and graphic contexts where width is the feature.',
    classification:    ['sans-serif', 'display'],
    subClassification: 'Multi-Width Display Grotesque',
    personalityTags:   ['Loud', 'Authoritative', 'Expressive', 'Raw', 'Functional'],
    useCaseTags:       ['Poster', 'Signage', 'Headline', 'Branding', 'Logo'],
    width:             'extended',
    xHeight:           'tall',
    contrast:          ['monolinear'],
    typefaceURL:       'https://www.eastofrome.com/fonts/tusker-pro',
    hasItalics:        true,
    rawKeywords:       ['East of Rome', 'EOR', 'Lewis McGuffie', '2017', 'Tusker Pro', 'Tusker Grotesk', 'duplexed', '9000', 'extended grotesque', 'display grotesque', 'Super', 'Cyrillic', 'Greek'],
  },
];

module.exports = { FOUNDRY, FOUNDRY_ID, SHARED, TYPEFACES };
